### ISSUE TITLE
group ``/metadata`` does not have a child named ``artist_terms_freq``

### ISSUE THREAD

**Issue by piyushkhemka** [tbertinmahieux/MSongsDB#5]
Hello

I am trying to convert the .h5 files to CSV or json in order to do some data processing on them. For this, I am making use of the Python Source files.

After making changes to some of the outdated pytables code (for eg replacing openFile with open_file etc.), I am still getting errors like these:

```
group ``/metadata`` does not have a child named ``artist_terms_freq``

group ``/metadata`` does not have a child named ``artist_terms``
```

Is there a way to resolve them? Thanks

**Comment by dpwe** [comment]
Can you be more specific about how to reproduce the error?  What functions
are you trying to run?

  DAn.

**Comment by dpwe** [comment]
BTW, I did not need to modify any of the tables code (e.g. openFile).
Here's the version I have:

>>> import tables

>>> print tables.__version__

3.2.2

>>>

What do you get on your system?

  DAn.

**Comment by piyushkhemka** [comment]
Ahh sorry. I jumped the gun a bit.

I am trying to run the create_aggregate_file in the pythonsrc folder.

The syntax I am using is this:
python create_aggregate_file.py /location/to/the/million-song-dataset songs.csv

I am on Python version 2.7 and tables version 3.3.0


This is the exact stack trace of the error.
`Aggregate file created, we start filling it.
Traceback (most recent call last):
  File "create_aggregate_file.py", line 100, in <module>
    HDF5.fill_hdf5_aggregate_file(h5,allh5,summaryfile=False)
  File "/Users/piyushkhemka/Downloads/MSongsDB-master/PythonSrc/hdf5_utils.py", line 272, in fill_hdf5_aggregate_file
    h5.root.metadata.artist_terms_freq.append( get_artist_terms_freq(h5tocopy,songidx) )
  File "/Users/piyushkhemka/Downloads/MSongsDB-master/PythonSrc/hdf5_getters.py", line 175, in get_artist_terms_freq
    return h5.root.metadata.artist_terms_freq[h5.root.metadata.songs.cols.idx_artist_terms[songidx]:
  File "/usr/local/lib/python2.7/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/usr/local/lib/python2.7/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/usr/local/lib/python2.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/metadata`` does not have a child named ``artist_terms_freq```



It's a little weird that you don't need to change the openFiles in your code to open_file because otherwise I get this error

`Traceback (most recent call last):
  File "create_aggregate_file.py", line 95, in <module>
    summaryfile=False)
  File "/Users/piyushkhemka/Downloads/MSongsDB-master/PythonSrc/hdf5_utils.py", line 441, in create_aggregate_file
    h5 = tables.openFile(h5filename, mode='w', title='H5 Song File')
AttributeError: 'module' object has no attribute 'openFile'`

Thanks
Piyush

**Comment by dpwe** [comment]
OK.  I get the same result (without modifying my code - I guess openFile
got removed between tables 3.2.2 and your tables 3.3.0).

Anyway, the problem is, I think, that scanning from the MillionSongDataset
root includes scanning the AdditionalFiles directory, which contains one
summary hdf5 file, which does not have all the fields.  If you restrict to
the data subdirectory, it works:

dpwe@dpwe-macbookpro2:~/projects/MSongsDB/PythonSrc$ python
create_aggregate_file.py /Users/dpwe/Downloads/MillionSongSubset/data
songs.h5

need pg module and MBrainzDB folder of Python source code if you

want to use musicbrainz related functions, e.g. fill_hdf5_from_musicbrainz

found 10000 H5 files.

Aggregate file created, we start filling it.

It's still running, but the point is that it's successfully scanning the
files.

  DAn.

**Comment by piyushkhemka** [comment]
Thanks a ton Dan. Restricting it to the /data folder did the trick.

**Comment by piyushkhemka** [comment]
Spoke too soon. The code works and extracts the data to the csv. However, when I open the CSV I only see garbled data.

![screen shot 2016-11-25 at 6 08 17 pm](https://cloud.githubusercontent.com/assets/4021220/20636395/430e205e-b33a-11e6-9438-6df2024ab3e6.png)

Does this code only aggregate all the h5 files and concatenate them? I thought it was converting them to ascii as well. Could you recommend how to convert them to json or csv?

Sorry, but the code & readme aren't documented very well and I have no idea how to proceed.

**Comment by dpwe** [comment]
Yes, the code writes an h5 file. Sorry, I meant to mention this when I saw
your output file was called csv. I'm not sure what gave you the idea it
would write ascii.

It would probably be relatively simple to write your own version of the
aggregate function that writes the fields out in ascii or whatever you
want. You can see how it opens each file and reads all the included fields.
But I don't think there's anything we released to do that.

DAn.

**Comment by piyushkhemka** [comment]
Understood. Thanks a lot Dan. You were very helpful.
